# fly.toml app configuration file generated for flybg on 2024-09-13T16:24:56+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flybg'
primary_region = 'ord'
kill_signal = 'SIGTERM'

[build]

[deploy]
strategy = 'bluegreen'

[env]
PHX_HOST = 'flybg.fly.dev'
PORT = '8080'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[http_service.concurrency]
type = 'connections'
hard_limit = 1000
soft_limit = 1000

[[http_service.checks]]
interval = '15s'
timeout = '1s'
grace_period = '2s'
method = 'GET'
path = '/healthcheck'

[[vm]]
memory = '2gb'
cpu_kind = 'performance'
cpus = 1
