# fly.toml app configuration file generated for bluegreen on 2024-09-12T15:28:35+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bluegreen'
primary_region = 'sin'
kill_signal = 'SIGTERM'

[build]

[deploy]
  strategy = 'bluegreen'

[env]
  PHX_HOST = 'bluegreen.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

  [[http_service.checks]]
    interval = '15s'
    timeout = '1s'
    grace_period = '2s'
    method = 'GET'
    path = '/healthcheck'

[[vm]]
  memory = '2gb'
  cpu_kind = 'performance'
  cpus = 1
